Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 125
Metrics/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 25
Style/Documentation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
